@hostname = localhost
@port = 2222
@host = {{hostname}}:{{port}}
@api = api/v1/
@contentType = application/json


### ROVERS
POST http://{{host}}/{{api}}solve/rovers HTTP/1.1
content-type: {{contentType}}


{
    "topRight": "5 5",
    "firstPoint": "1 2 N",
    "movesr1": "LMLMLMLMM"
}
### ROVERS
POST http://{{host}}/{{api}}solve/rovers HTTP/1.1
content-type: {{contentType}}


{
    "topRight": "5 5",
    "firstPoint": "3 3 E",
    "movesr1": "MMRMMRMRRM"
}